# Generated by Django 3.1.5 on 2021-01-29 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flashapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 6, 10, 24, 218998, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='card',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 6, 10, 24, 219023, tzinfo=utc)),
        ),
    ]
