# Generated by Django 3.1.5 on 2021-01-29 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flashapp', '0002_auto_20210129_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 7, 58, 4, 646597, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 7, 58, 4, 646628, tzinfo=utc)),
        ),
    ]
